# Generated by Django 3.1.7 on 2021-09-22 16:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('portrait', models.ImageField(upload_to='portraits/')),
                ('birthday', models.DateField()),
                ('website', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('degree', models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Master', 'Master'), ('Senior', 'Senior')], max_length=100)),
                ('phEmailone', models.EmailField(max_length=254)),
                ('freelance', models.BooleanField()),
                ('desc', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Facts_Scils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.PositiveIntegerField()),
                ('css', models.PositiveIntegerField()),
                ('bootstrap', models.PositiveIntegerField()),
                ('javascript', models.PositiveIntegerField()),
                ('django', models.PositiveIntegerField()),
                ('photoshop', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Fact and Scil',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('project_date', models.DateField()),
                ('project_url', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('poster', models.ImageField(null=True, upload_to='portfolio_posters/')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='*')),
                ('desc', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('Sumary', 'Sumary'), ('Education', 'Education'), ('Professional_Experience', 'Professional_Experience')], max_length=50, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=100, null=True)),
                ('desc', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name': 'Resume',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='testimonials_poster/')),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Portfolio_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('experiences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_me.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio_Image',
                'verbose_name_plural': 'Portfolio_Images',
            },
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('experiences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_me.resume')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
    ]
