# Generated by Django 3.2.7 on 2021-09-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facts_scils',
            old_name='javascript',
            new_name='cpp',
        ),
    ]
